version: '3'
services:
  app:
    build:
        context: node
    container_name: app
    networks: 
      - node-network
    volumes:
      - ./node:/usr/scr/app
    tty: true 
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks :
      - node-network

  nginx:
    build:
      context: nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
     - app
    links: 
     - app    

networks:
  node-network:
    driver: bridge    
     

